declare function _getMobileProvidersDatabase(): any;
declare function _findProviderForMccMnc(operatorName: any, operatorCode: any): any;
declare function _findProviderForSid(sid: any): any;
declare const Gio: any;
declare const GObject: any;
declare const NM: any;
declare const NMA: any;
declare const loadInterfaceXML: any;
declare let _mpd: any;
declare const ModemGsmNetworkInterface: any;
declare const ModemGsmNetworkProxy: any;
declare const ModemCdmaInterface: any;
declare const ModemCdmaProxy: any;
declare var ModemBase: any;
declare var ModemGsm: any;
declare var ModemCdma: any;
declare const BroadbandModemInterface: any;
declare const BroadbandModemProxy: any;
declare const BroadbandModem3gppInterface: any;
declare const BroadbandModem3gppProxy: any;
declare const BroadbandModemCdmaInterface: any;
declare const BroadbandModemCdmaProxy: any;
declare var BroadbandModem: any;
//# sourceMappingURL=modemManager.d.ts.map