declare function getAppFavorites(): any;
declare const Shell: any;
declare const ParentalControlsManager: any;
declare const Signals: any;
declare const Main: any;
declare const RENAMED_DESKTOP_IDS: {
    'baobab.desktop': string;
    'cheese.desktop': string;
    'dconf-editor.desktop': string;
    'empathy.desktop': string;
    'eog.desktop': string;
    'epiphany.desktop': string;
    'evolution.desktop': string;
    'file-roller.desktop': string;
    'five-or-more.desktop': string;
    'four-in-a-row.desktop': string;
    'gcalctool.desktop': string;
    'geary.desktop': string;
    'gedit.desktop': string;
    'glchess.desktop': string;
    'glines.desktop': string;
    'gnect.desktop': string;
    'gnibbles.desktop': string;
    'gnobots2.desktop': string;
    'gnome-boxes.desktop': string;
    'gnome-calculator.desktop': string;
    'gnome-chess.desktop': string;
    'gnome-clocks.desktop': string;
    'gnome-contacts.desktop': string;
    'gnome-documents.desktop': string;
    'gnome-font-viewer.desktop': string;
    'gnome-klotski.desktop': string;
    'gnome-nibbles.desktop': string;
    'gnome-mahjongg.desktop': string;
    'gnome-mines.desktop': string;
    'gnome-music.desktop': string;
    'gnome-photos.desktop': string;
    'gnome-robots.desktop': string;
    'gnome-screenshot.desktop': string;
    'gnome-software.desktop': string;
    'gnome-terminal.desktop': string;
    'gnome-tetravex.desktop': string;
    'gnome-tweaks.desktop': string;
    'gnome-weather.desktop': string;
    'gnomine.desktop': string;
    'gnotravex.desktop': string;
    'gnotski.desktop': string;
    'gtali.desktop': string;
    'iagno.desktop': string;
    'nautilus.desktop': string;
    'org.gnome.gnome-2048.desktop': string;
    'org.gnome.taquin.desktop': string;
    'org.gnome.Weather.Application.desktop': string;
    'polari.desktop': string;
    'seahorse.desktop': string;
    'shotwell.desktop': string;
    'tali.desktop': string;
    'totem.desktop': string;
    'evince.desktop': string;
};
declare class AppFavorites {
    _parentalControlsManager: any;
    FAVORITE_APPS_KEY: string;
    _favorites: {};
    _onFavsChanged(): void;
    reload(): void;
    _getIds(): string[];
    getFavoriteMap(): {};
    getFavorites(): any[];
    isFavorite(appId: any): boolean;
    _addFavorite(appId: any, pos: any): boolean;
    addFavoriteAtPos(appId: any, pos: any): void;
    addFavorite(appId: any): void;
    moveFavoriteToPos(appId: any, pos: any): void;
    _removeFavorite(appId: any): boolean;
    removeFavorite(appId: any): void;
}
declare var appFavoritesInstance: any;
//# sourceMappingURL=appFavorites.d.ts.map