declare function getAppFromSource(source: any): any;
declare const Clutter: any;
declare const GLib: any;
declare const GObject: any;
declare const Graphene: any;
declare const Meta: any;
declare const Shell: any;
declare const St: any;
declare const AppDisplay: any;
declare const AppFavorites: any;
declare const DND: any;
declare const IconGrid: any;
declare const Main: any;
declare const Overview: any;
declare var DASH_ANIMATION_TIME: number;
declare var DASH_ITEM_LABEL_SHOW_TIME: number;
declare var DASH_ITEM_LABEL_HIDE_TIME: number;
declare var DASH_ITEM_HOVER_TIMEOUT: number;
declare var DashIcon: any;
declare var DashItemContainer: any;
declare var ShowAppsIcon: any;
declare var DragPlaceholderItem: any;
declare var EmptyDropTargetItem: any;
declare const DashIconsLayout: any;
declare const baseIconSizes: number[];
declare var Dash: any;
//# sourceMappingURL=dash.d.ts.map