declare function _isToday(date: any): boolean;
declare function _gDateTimeToDate(datetime: any): Date;
declare const Clutter: any;
declare const Gio: any;
declare const GLib: any;
declare const GnomeDesktop: any;
declare const GObject: any;
declare const GWeather: any;
declare const Pango: any;
declare const Shell: any;
declare const St: any;
declare const Util: any;
declare const Main: any;
declare const PanelMenu: any;
declare const Calendar: any;
declare const Weather: any;
declare const System: any;
declare const loadInterfaceXML: any;
declare function NC_(context: any, str: any): string;
declare const T_: any;
declare const MAX_FORECASTS: 5;
declare const EN_CHAR: "–";
declare const ClocksIntegrationIface: any;
declare const ClocksProxy: any;
declare var TodayButton: any;
declare var EventsSection: any;
declare var WorldClocksSection: any;
declare var WeatherSection: any;
declare var MessagesIndicator: any;
declare var FreezableBinLayout: any;
declare var CalendarColumnLayout: any;
declare var DateMenuButton: any;
//# sourceMappingURL=dateMenu.d.ts.map