declare function _getAutoCompleteGlobalKeywords(): string[];
declare function objectToString(o: any): string;
declare const Clutter: any;
declare const Cogl: any;
declare const Gio: any;
declare const GLib: any;
declare const GObject: any;
declare const Graphene: any;
declare const Meta: any;
declare const Pango: any;
declare const Shell: any;
declare const St: any;
declare const Signals: any;
declare const System: any;
declare const History: any;
declare const ExtensionUtils: any;
declare const PopupMenu: any;
declare const ShellEntry: any;
declare const Main: any;
declare const JsParse: any;
declare const ExtensionState: any;
declare const CHEVRON: ">>> ";
declare var commandHeader: string;
declare const HISTORY_KEY: "looking-glass-history";
declare var AUTO_COMPLETE_DOUBLE_TAB_DELAY: number;
declare var AUTO_COMPLETE_SHOW_COMPLETION_ANIMATION_DURATION: number;
declare var AUTO_COMPLETE_GLOBAL_KEYWORDS: string[];
declare const LG_ANIMATION_TIME: 500;
declare const CLUTTER_DEBUG_FLAG_CATEGORIES: Map<string, {
    argPos: number;
    exclude: string[];
}>;
declare var AutoComplete: {
    new (entry: any): {
        _entry: any;
        _lastTabTime: any;
        _processCompletionRequest(event: any): void;
        _entryKeyPressEvent(actor: any, event: any): any;
        additionalCompletionText(text: any, head: any): void;
    };
};
declare var Notebook: any;
declare var ObjLink: any;
declare var Result: any;
declare var WindowList: any;
declare var ObjInspector: any;
declare var RedBorderEffect: any;
declare var Inspector: any;
declare var Extensions: any;
declare var ActorLink: any;
declare var ActorTreeViewer: any;
declare var DebugFlag: any;
declare var ClutterDebugFlag: any;
declare var MutterPaintDebugFlag: any;
declare var MutterTopicDebugFlag: any;
declare var UnsafeModeDebugFlag: any;
declare var DebugFlags: any;
declare var LookingGlass: any;
//# sourceMappingURL=lookingGlass.d.ts.map